# SVM Error Analysis

### 1. Imports and setting up the new error dataframe

In [1]:
import pandas as pd 
import joblib

In [2]:
df_test = pd.read_csv("../datasets/clinical_cases_test.csv")    # importing the test set

# importing models
model = joblib.load("../models/clinical_classifier.joblib")
vectorizer = joblib.load("../models/tfidf_vectorizer.joblib")

In [3]:
X_test = df_test["medical_abstract"]

# vectorizing the abstracts
X_test_vec = vectorizer.transform(X_test)

In [4]:
predictions = model.predict(X_test_vec)     # obtaining the predictions

In [5]:
# starting error analysis creating a new copy of original df but where predictions are all wrong
errors = df_test[predictions != df_test["condition_label"]].copy()

errors["predicted_label"] = predictions[predictions != df_test["condition_label"]]

In [6]:
errors.shape    # errors count

(1431, 3)

### 2. Work with errors to analyze the patterns

In [7]:
# visualizing full text rows to get better reasoning of vectorizer errors 
pd.set_option("display.max_colwidth", None)

In [8]:
errors[[
    "medical_abstract",
    "condition_label",
    "predicted_label"
]].head(10)

,medical_abstract,condition_label,predicted_label
0,"Obstructive sleep apnea following topical oropharyngeal anesthesia in loud snorers. Previous studies support the presence of an upper airway reflex mechanism that contributes to the maintenance of upper airway patency during sleep. We investigated the possibility that interference with this reflex mechanism contributes to the development of obstructive sleep apnea. Eight otherwise asymptomatic snorers (seven male and one female), age 39 +/- 5.3 yr (mean +/- SEM), underwent overnight sleep studies on three successive nights. An acclimatization night was followed by two study nights randomly assigned to control (C) and oropharyngeal anesthesia (OPA). On the OPA night topical anesthesia was induced using 10% lidocaine spray and 0.25% bupivacaine gargle. A saline placebo was used on night C. All subjects slept well on both study nights (mean sleep duration was 6.2 h on both study nights), and sleep stage distribution was similar on both nights. Obstructive apneas and hypopneas (OAH) rose from 114 +/- 43 during C to 170 +/- 49 during OPA (p less than 0.02). Central apneas and hypopneas (CAH) were unchanged between the two nights (8 +/- 4.9 versus 7 +/- 3). The duration of OAH was similar on both study nights (20 +/- 1.9 s during C versus 20 +/- 1.5 s during OPA). The frequency of movement arousals terminating OAH tended to be higher during OPA (7 +/- 2.9/h) than during C (3 +/- 0.7); P = NS. The frequency of oxyhemoglobin desaturations was also higher during OPA (5 +/- 2.1/h) than during C (3 +/- 1.4), p less than 0.07.",3,5
1,"Neutrophil function and pyogenic infections in bone marrow transplant recipients. In a consecutive entry trial, the incidence and time course of decreased neutrophil function was assessed in 20 patients treated with allogeneic bone marrow transplantation (BMT). The aim of the study was to assess the prognostic value of low neutrophil function for late pyogenic infections. Chemotaxis, superoxide production, and phagocytic-bactericidal activity were studied before and 2, 6, 9, and 12 months after BMT. Skin window migration was quantitatively assessed 2 months after BMT. Infectious complications were recorded prospectively with preset criteria during 1 year. Six of the 20 leukemic patients had defective neutrophil function before BMT. Two months after BMT all 10 patients with greater than stage II graft-versus-host disease (GVHD), and 6 of 10 patients with less than or equal to stage II GVHD had at least one decreased function. At this time, patients with subsequent pyogenic infections had lower chemotaxis (P less than .05), phagocytic-bactericidal activity (P less than .005), and superoxide production (P less than .025) than those without. Defective skin window migration and combined defects were predictive for late pyogenic infections. At 9 months all tests were normal in seven patients surviving without GVHD. In contrast, at 9 months three of three patients, and at 1 year two of three with chronic GVHD had still decreased neutrophil function. In conclusion, neutrophil function is frequently impaired during the first months after BMT. Combined neutrophil defects predispose to pyogenic infections and indicate the patient at risk.",5,1
2,"A phase II study of combined methotrexate and teniposide infusions prior to reinduction therapy in relapsed childhood acute lymphoblastic leukemia: a Pediatric Oncology Group study. Teniposide (VM-26) can increase intracellular methotrexate (MTX) and its polyglutamate derivatives in vitro and thus has the potential to improve the therapeutic index of regimens containing MTX. In this phase II study, children and adolescents with acute lymphoblastic leukemia (ALL) in first or second marrow relapse were randomly assigned to receive either simultaneous (n = 11) or sequential (n = 12) continuous infusions of MTX and VM-26 prior to reinduction. Infusions of VM-26 were begun 12 hours after completion of MTX infusion in the sequential group. Dosages were individually adjusted to maintain plasma concentration levels of 10 microns for MTX and 15 microns for VM-26; total infusion times were 24 and 72 hours, respectively. Significant toxicity in the first six patients who received the scheduled 72-hour VM-26 infusion (including one drug-related death) prompted a 50% reduction in infusion duration. The reduced dose was associated with similar but more manageable toxicity. Examination of bone marrow aspirates 10 days after therapy was begun showed one complete and two partial marrow remissions; a fourth patient who had an aplastic marrow on day 10 received no further chemotherapy and had a complete remission (CR) documented on day 31. There was no obvious clinical advantage associated with either infusion schedule, although small sample sizes preclude definitive conclusions. The 17% response rate to the MTX/VM-26 therapeutic window in patients with refractory disease suggests the need for further investigation to evaluate alternative schedules and concomitant therapy for this drug combination.",5,1
4,"Paraneoplastic vasculitic neuropathy: a treatable neuropathy. Paraneoplastic vasculitic neuropathy has been recently described. We report the first case of this disorder which responded both clinically and electrophysiologically to cyclophosphamide treatment. A 54-year-old woman with a history of metastatic endometrial carcinoma in remission had asymmetrical polyneuropathy, electrophysiological findings consistent with a diffuse axonal neuropathy, high sedimentation rate and spinal fluid protein, and microvasculitis with axonal degeneration on nerve biopsy. The patient was treated with 150 mg of cyclophosphamide daily with gradual clinical and electrophysiological improvement.",4,1
7,"Questionable role of CNS radioprophylaxis in the therapeutic management of childhood rhabdomyosarcoma with meningeal extension. A series of 15 consecutive children with head and neck nonorbital rhabdomyosarcoma (RMSA) with meningeal extension were prospectively treated with chemotherapy consisting of Adriamycin (doxorubicin; Adria Laboratory, Columbus, OH) (ADM), vincristine (VCR), cyclophosphamide (CPM), and dactinomycin (DACT) followed by radiotherapy (60 Gy) to the primary tumor volume, along with intrathecal methotrexate (IT MTX). Thirteen of 15 responded to preradiation chemotherapy. Four of 13 relapsed. Relapse occurred at the level of the primary tumor in three of four. The 3-year progression-free survival (PFS) was 59%, similar to that achieved in a previous series treated with a comparable therapeutic approach that also included whole-brain radiotherapy as a prophylaxis of possible occult meningeal seeding. It is concluded that CNS prophylaxis with radiotherapy is questionable in the management of childhood RMSA with meningeal extension.",1,3
8,"Reversibility of hepatic fibrosis in experimentally induced cholestasis in rat. The reversibility of hepatic fibrosis was investigated in an experimental model of extrahepatic cholestasis in the rat after common bile duct ligation for 2 weeks, followed by bilioduodenal anastomosis for 3 weeks. Bile duct ligation resulted in a transitory marked elevation in the serum concentration of 5'-nucleotidase, alkaline phosphatase, and bilirubin during the first 3 days. Then these levels decreased to threefold, twofold, and 100-fold the normal values, respectively, during the following 4 weeks. Histologic examination of the liver disclosed extensive bile duct proliferation and the formation of periportal fibrosis, with only slight inflammation and necrosis. The distribution of the major components of the hepatic extracellular matrix was analyzed 2 weeks after bile duct ligation, using the indirect immunoperoxidase method. Fibrous septa were found to be strongly stained for collagens I, pro-III, III and IV, fibronectin, and laminin. The most intense staining was found in enlarged periportal areas, collagen IV and laminin being particularly abundant around newly formed bile ducts. These changes paralleled high steady-state levels of alpha 1(I) and alpha 1(IV) collagen and B2 chain laminin mRNAs. Relief of the obstruction for 2 weeks resulted in a shift in the serum concentration of 5'-nucleotidase, alkaline phosphatase, and bilirubin toward normal values. A dramatic resorption of bile duct proliferations and periportal fibrosis were observed. Three weeks after bile duct repermeabilization, immunohistochemical study showed that the pattern of distribution of extracellular matrix components was almost normal, except for collagen IV, which remained abundant in the sinusoids when compared with the normal liver. In parallel, the steady-state B2-chain laminin mRNA level became lower than in cholestatic livers, whereas alpha 1(I) and alpha 1(IV) mRNAs were almost undetectable. These results show that hepatic fibrosis induced by experimental extrahepatic cholestasis in rat disappears in less than 3 weeks after relief of bile duct obstruction, suggesting that an active degradation of matrix protein occurs, except for collagen IV in the sinusoid.",5,2
9,"Current status of duplex Doppler ultrasound in the examination of the abdominal vasculature. Duplex Doppler ultrasound has come to play a central role in the diagnosis of a broad spectrum of vascular diseases such as carotid artery occlusive disease and deep vein thrombosis. The role of duplex Doppler in the evaluation of intra-abdominal vascular disease remains unclear. This article summarizes the current status of duplex scanning in the investigation of the mesenteric arteries, the renal arteries, and the portal venous system. The examination is technically demanding, operator-dependent, time-consuming, and frequently unsatisfactory due to bowel gas, obesity, complex anatomy, or postoperative alterations in the normal anatomic patterns. Its advantages reside primarily in the absence of toxicity and in the generation of physiologic as well as anatomic information. In centers with the proper instrumentation and a skilled technician, duplex examination can be useful in the diagnosis and management of abdominal vascular disease and avoids the inherent dangers of contrast angiography.",2,4
10,"The importance of congenital hypertrophy of the retinal pigment epithelium in familial adenomatous polyposis. We describe a family with familial adenomatous polyposis (FAP) and congenital hypertrophy of the retinal pigment epithelium (RPE). Three of five members with FAP showed flat, well-demarcated, round to oval pigmented patches of congenital hypertrophy of the RPE. We stress the importance of congenital hypertrophy of the RPE as a clinical marker in identifying patients with FAP since they are at risk for cancer.",5,1
12,"Gentamicin iontophoresis in the treatment of bacterial otitis externa in the guinea pig model. Pseudomonas otitis externa is one of the most common infections treated by otolaryngologists. Infections induced in 30 guinea pigs appeared similar to that seen in humans. The ears were then placed into four treatment groups: group A, which received a single cleaning; group B, which received a single cleaning followed by gentamicin drops 4 times daily; group C, which received a single cleaning followed by a single gentamicin iontophoresis treatment; and group D, the control group, which received no treatment. Infections were analyzed by grading edema, purulence, and erythema. An average of 10.2 days was required for control group to return to normal appearance. Groups A, B, and C had mean resolution times of 5.9, 4.7, and 4.3 days, respectively. Gentamicin iontophoresis appears to be promising, with results as good as drop therapy in otitis externa in the guinea pig model.",5,4
16,"A useful technique for measurement of back strength in osteoporotic and elderly patients. Improvement of back extensor strength (BES) can be used as a therapeutic method for patients with chronic back pain and osteoporosis. The method of evaluation must be reliable and accurate without compromising the condition of the patient. We report the development of a back isometric dynamometer (BID-2000) designed specifically by two of us to address these concerns in elderly patients with osteopenia or osteoporosis. As the demographics of the general population change, increasing numbers of patients will need the type of monitoring that the BID-2000 provides. Aging has been shown to cause a reduction in the number of functional muscle motor units. To examine this effect on BES, we tested 50 normal, healthy women who were 30 to 79 years old. Proper testing of BES in patients with fragile vertebrae should include isometric measurement in the prone position, maneuverability of the device to allow comfortable positioning of the patient, and simplicity of technique to minimize repetitious performance of maximal contraction. The BID-2000 incorporates each of these features and also provides meaningful results inexpensively. The device offers a safe, reliable (coefficient of variation = 2.33%), and valid (P = 0.001) method of evaluation. The results of our study demonstrated moderate, steady reduction of BES with increasing age and with each successive decade.",5,3

The results clearly show how the model isn't doing necessarily bad, besides the low 50% accuracy trend.

Most medical abstracts contain multiple words from multiple topics, about the different labels we have. 
It would be better to add maybe more labels to the downloaded dataset we got, or search already for better technologies, like transformers. 

Surely the lack of context reading from the model is a difficult flaw, but let's deep dive through the complete set first to see the full trend on the errors.

In [9]:
# random 10 samples from the set
errors[[
    "medical_abstract",
    "condition_label",
    "predicted_label"
]].sample(10, random_state=42)  # remove random_state=42 to check different results for each execution

,medical_abstract,condition_label,predicted_label
244,"Synchronous reconstruction for combined aortoiliac and femoropopliteal occlusive lesions. The role of proximal bypass. Between January 1984 and December 1986, 31 patients underwent synchronous revascularization (SR) because of the serious clinical condition of a lower limb and presence of arteriographically visible lesions. Average follow-up was 30 months. Operative mortality was 10%. Two patient populations were identified: Group I (N = 13): patients who underwent ilio-femoral or aorto-femoral proximal revascularization (PR); Group II (N = 18): patients who had axillo-femoral PR. Group I patients were younger than those in Group II (64 yr versus 72 yr; p less than 0.01). An association of pre-operative risk factors (arterial hypertension; coronary, renal or respiratory insufficiency) was twice as frequent in Group II as in Group I (p less than 0.02). The rate of SR compared to PR alone was 15%. However, there was no statistically significant difference between Groups I and II. Comparison of the actuarial survival curves for patients ahd the patency rates of SR in Groups I and II failed to reveal any statistically significant differences. Axillo-femoral bypass can be used for PR when SR is necessary in high risk patients.",4,5
2409,"Pathomechanism, pathogenesis, and results of treatment in cervical spondylotic myelopathy caused by dynamic canal stenosis. In this study, the pathomechanism and pathogenesis of dynamic canal stenosis caused by cervical instability in patients with cervical spondylotic myelopathy and the validity of the concept of instability are clarified by analyzing the results of treatment in 53 cases. In cases of cervical spondylotic myelopathy caused by dynamic canal stenosis, the authors found that the posterior slide of the vertebral body occurs as a result of degeneration in the cervical spine due to aging changes, and that the dynamic sagittal diameter of the spinal canal decreases with an increase of the degree of posterior slide. This is followed by gradual aggravation of the clinical symptoms. Continuous cervical traction was found to be the first choice of treatment. Surgical treatment is indicated in cases in which the traction was ineffective, or even when it was effective, in cases in which the Japanese Orthopaedic Association (JOA) score remained low or when there was a tendency toward rapid aggravation of symptoms. It was demonstrated that the shorter the duration of the myelopathy, the better the results of treatment obtained. A limit of the dynamic sagittal diameter of the spinal canal of 12 mm was considered as valid.",3,5
943,"Comparison of symptom characteristics of indwelling ureteral catheters. The signs and symptoms produced by 4 different types of 7F double pigtail catheters, including Cook polyurethane pigtail stent, Surgitek Silitek Uropass, Cook C-Flex and Van-Tec Soft stent, were analyzed prospectively. The stents were placed in 45 men and 28 women ranging in age from 23 to 72 years old. A total of 44 catheters had a suture attached to the bladder end of the catheter, which exited from the urethral meatus to facilitate removal. The remaining 29 catheters had no suture attached. Symptoms were evaluated at 2 and 6 days after insertion and 1 week following removal of the catheter, and included urinary frequency, nocturia, hematuria, flank pain, suprapubic pain, dysuria and pain on removal of the catheter. Frequency and nocturia were evaluated in minutes, pain was graded on a subjective scale of 0 (no pain) to 10 (severe pain), and dysuria and hematuria were assessed qualitatively. There were no significant differences among the 4 types of catheters in terms of frequency, nocturia, hematuria, flank pain, suprapubic pain and dysuria. In addition, there was no significant difference in urinary symptoms between catheters with and without a suture at either 2 or 6 days after insertion nor was there any difference in pain on removal of catheters with (mean 3.9) and without (mean 5.0) suture. We found that catheter composition and use of suture to facilitate removal did not significantly affect patient morbidity.",3,5
707,"Physiologic peripheral pulmonic stenosis in infancy. We studied 14 premature infants with the clinical diagnosis of peripheral pulmonic stenosis (PPS) and 15 normal full-term neonates by echocardiographic Doppler examinations. The PPS group had an average main pulmonary artery (PA) diameter similar to the control group (0.91 vs 0.96 cm, difference not significant), but had smaller branch PA diameters: right PA = 0.41 vs 0.50 cm, p less than 0.001, and left PA = 0.41 vs 0.49 cm, p less than 0.001. The PPS group also had greater peak velocities in the main PA (76 vs 63 cm/s, p less than 0.05), right PA (193 vs 118 cm/s, p less than 0.001) and left PA (187 vs 123 cm/s, p less than 0.001). Similarly, the ratio of peak velocity in the branch/main PA was greater for the PPS group: right/main PA peak velocity = 2.91 vs 1.92, p less than 0.01, and left/main PA peak velocity = 2.73 vs 1.99, p less than 0.05. The calculated right ventricular output for the PPS group was more than the control group: 437 vs 261 ml/min/kg, p less than 0.001. Hematocrits were not done on the control group, but the PPS group had an average hematocrit which was low (34%). It is concluded that patients with PPS have mild underdevelopment of the PA branches, with consequent increased flow velocity and turbulent flow. This turbulent flow may be contributed to by increased cardiac output and mild anemia.",4,5
2633,"Role of new anticoagulants as adjunctive therapy during thrombolysis. Procoagulant activity may persist during coronary thrombolysis and result in either delay in the time to recanalization or recurrent thrombosis. Although heparin and aspirin form the mainstay of current therapy, recurrent thrombosis occurs despite adjunctive heparin therapy during thrombolysis. Newer agents that inhibit thrombin by antithrombin III-independent mechanisms, or that inhibit earlier steps in the coagulation cascade, have been shown to be effective in the experimental preparation of coronary thrombolysis. Because heparin-antithrombin III is a relatively inefficient inhibitor of thrombin bound to fibrin, agents such as hirudin or small peptide inhibitors of the thrombin-active site appear to be more effective inhibitors of clot-associated thrombin activity. Inhibition of early steps in the coagulation cascade with the inhibitor of tissue factor-factor VIIa complex, or with activated protein C, also appears to be an effective anticoagulant strategy. In experimental preparations all of these agents have shown superiority in preventing recurrent thrombosis compared with heparin, and in some cases they appear to accelerate the rate of clot lysis.",5,4
1340,"Oral indomethacin for acute renal colic. A number of studies have suggested that nonsteroidal antiinflammatory agents can relieve renal colic by a mechanism of action different from that of narcotics, offering the potential advantage of avoiding narcotic side-effects such as alteration of mental status. The authors prospectively administered oral indomethacin, 50 mg, to 25 nonvomiting patients with acute renal colic due to a documented stone. Eleven patients group (I) received the drug in an unblinded, nonrandomized fashion after failure of oral or parenteral narcotics to provide satisfactory pain relief, either at home or in the emergency department. In 14 additional patients group (II) indomethacin was given as the only initial treatment. Pain intensity before and after treatment was reported using a 1-to-10 scale. In group I, pain decreased from 5.8 +/- 2.7 to 3.6 +/- 3.8 (P less than .02). Six of the 11 patients reported a decrease in pain intensity of 50% or more, which occurred within 25 +/- 11 minutes, and in 5 of these 6, pain decreased to a 0 or 1 level. In group II, pain decreased from 7.6 +/- 1.5 to 4.6 +/- 4.0 (P less than .008). Eight of the 14 patients reported a decrease in pain intensity of 50% or more, which occurred within 40 +/- 14 minutes, and in 5 of these 8 pain decreased to a 0 or 1 level. Among all 25 patients who received indomethacin, pain relief was not significantly associated with the duration of pain before treatment or with patient age or sex. There was a trend for pretreatment pain intensity to be higher among nonresponders (P = .07).",2,5
1512,"Reverse coitus: mechanism of urethral injury in male partner. Reverse coitus, a rarely used sexual position, makes the male urethra more vulnerable to injury from the pubic arch and symphysis pubis of the female partner. Severe pain, bleeding and immediate detumescence were observed in 3 patients. The lesion usually occurred at the fossa navicularis, responded well to conservative management and did not hinder micturition. Potency has been well preserved in all 3 patients.",3,5
1057,"Independence of pressure reactivity from pressure levels in Tecumseh, Michigan. The relation between blood pressure level and reactivity to mental arithmetic and isometric exercise was investigated in 169 men and 120 women (average age, 32.3 years) from the village of Tecumseh, Mich. In the entire population, the correlation between baseline blood pressure and blood pressure response to both stressors was not significant. Blood pressure reactivity to both stressors was not increased in participants with borderline hypertension (one clinic reading of more than 140 mm Hg systolic and/or 90 mm Hg diastolic). When subjects were classified according to blood pressure response (below and above the 80th percentile), the hyperreactors to mental and physical stress had normal baseline blood pressure values. The hyperreactors also had clinic-to-home blood pressure differences similar to those of the rest of the population. Participants who had borderline hypertension at age 32 years had significantly elevated blood pressures at ages 5, 8, 12, 21, and 22 years. Those who were hyperreactors at age 32 years had normal blood pressures as children and young adults. Results of the present study lend no support to an association between higher blood pressures and blood pressure hyperreactivity. Study participants in Tecumseh will be recalled for future examinations. The independence of blood pressure levels from blood pressure reactivity offers a unique opportunity to prospectively evaluate their separate effects on cardiovascular morbidity.",5,4
142,"Permanent external striated sphincter stents in patients with spinal injuries. Nine patients with complete quadriplegia underwent external striated sphincter stenting with the Wallstent in place of an external striated sphincterotomy. Although suprapubic catheters were placed to provide an outlet should problems develop with the stent, they were successfully removed within 6 weeks in all but 1 patient. Complete bladder emptying with reduced voiding pressures was achieved, together with a significant reduction in the duration of hyper-reflexic contractions. Epithelialisation of the stent was almost complete within 3 months and intermittent catheterisation or endoscopy (and resection) is possible through the stent. Although this is a preliminary report of this new technique, it is hoped that sphincter stenting will provide a rapid, safe and effective method of treating high pressure hyper-reflexia and detrusor sphincter dyssynergia in quadriplegic patients.",3,5
1115,"Mitral valve disruption following percutaneous balloon valvuloplasty. Two cases of massive mitral regurgitation due to mitral valve disruption following percutaneous balloon valvuloplasty are reported. This severe complication occurred in two elderly women with recurrent mitral stenosis after previous surgical commissurotomy. Due to their unstable hemodynamic and clinical condition, both patients underwent emergency valve replacement. At surgery, the commissures appeared fused and heavily calcified; the chordae tendineae thickened, shortened, and fused; and the leaflets presented a large tear with sheared edges. Because the technical aspects of both procedures were unremarkable, the anatomic features of the mitral valve seemed to affect the occurrence of severe mitral regurgitation. Percutaneous balloon valvuloplasty should be therefore applied carefully to patients with prior surgical valvotomy, in whom the structural alterations of the mitral apparatus may predispose to severe valvular damage.",5,4

In [10]:
model.coef_.shape   # number of rows and columns (class, feature) mantained as coef by the vectorizer

(5, 10000)

In [11]:
feature_names = vectorizer.get_feature_names_out()  # extracting the feature names to link them soon

feature_names.shape

(10000,)

In [ ]:
class_1_coefficients = model.coef_[0]   # class 1 analysis - neoplasms

top_indices = class_1_coefficients.argsort()[-10:][::-1]   # orders by value, takes top 10 in desc order 

for index in top_indices:
    print(feature_names[index], class_1_coefficients[index]) # prints in order token and weight value

cancer 3.415663419170131
carcinoma 2.4693072617165726
tumor 2.219889790102231
leukemia 2.2077102950566267
melanoma 1.9448796908052768
lipoma 1.7683111703002188
masses 1.6501601383282483
pheochromocytoma 1.6330084641485685
tumors 1.6266392991234062
sporadic 1.6088573930223042

Doing the same for the 5th class where the model makes more mistakes.

In [ ]:
class_5_coefficients = model.coef_[4] # class 5 analysis - general pathological 

top_indices = class_5_coefficients.argsort()[-10:][::-1]   # orders by value, takes top 10 in desc order 

for index in top_indices:
    print(feature_names[index], class_5_coefficients[index]) # prints in order token and weight value

hyperplasia 2.0084298787015453
postoperative 2.001001237125541
oat 1.7699176962889482
deletion 1.7342932563551778
chronic 1.7307154944668541
prompt 1.7278227099327934
constipation 1.6834104641158414
volumetric 1.614433119968741
cadaveric 1.5958785621388363
unknown 1.5580984449483979

The 5th class contains more heterogeneous words inside of it, compatible with multiple classes. Let's do a rapid comparison.

In [16]:
# analysis between class 1 and class 5 with joint df 
comparison = pd.DataFrame({ 
    "feature": feature_names,
    "class_1": model.coef_[0],
    "class_5": model.coef_[4]
})

comparison.sort_values("class_5", ascending=False).head(20) # first 20 words randomized

             feature   class_1   class_5
4477     hyperplasia -1.182261  2.008430
7176   postoperative -0.817699  2.001001
6397             oat -1.334141  1.769918
2599        deletion -0.782179  1.734293
1840         chronic -1.062135  1.730715
7418          prompt -0.530226  1.727823
2200    constipation -0.293476  1.683410
9836      volumetric -0.217213  1.614433
1526       cadaveric -0.377126  1.595879
9573         unknown -1.303168  1.558098
1021     arrhythmias  0.280860  1.553147
660           airway  0.035104  1.541995
1538         calculi -0.706450  1.534460
7787       recurrent -0.867955  1.528206
4290      hemorrhage -0.202247  1.510610
512            acute -0.990244  1.505421
4630  immunoglobulin -0.760211  1.492486
228               24 -0.288210  1.471199
6761         passage -0.314421  1.439774
9353  transformation -0.669178  1.436442

In [ ]:
# class 2 analysis - digestive system 
class_2_coefficients = model.coef_[1]

top_indices = class_2_coefficients.argsort()[-10:][::-1]

for index in top_indices:
    print(feature_names[index], class_2_coefficients[index])

cirrhosis 2.6993780426403196
gallstones 2.036745655926961
dysphagia 1.9689847120957922
capd 1.8016151146793273
gallbladder 1.7932453924261902
gallstone 1.7538939321747373
bowel 1.7276321810259199
diarrhea 1.7070324784412436
peritonitis 1.66500351172547
colitis 1.6406607344438777

In [ ]:
# class 3 analysis - nervous system 
class_3_coefficients = model.coef_[2]

top_indices = class_3_coefficients.argsort()[-10:][::-1]

for index in top_indices:
    print(feature_names[index], class_3_coefficients[index])

stroke 2.182159388759829
brain 1.796235997954152
meningeal 1.7706240786504897
neuromuscular 1.7701682943552142
fragile 1.757005565399594
headache 1.7279147054938289
pain 1.7241341728639605
meningitis 1.6512020524282462
syncope 1.6357605273068963
cerebral 1.6293600789644112

In [20]:
# class 4 analysis - cardiovascular 
class_4_coefficients = model.coef_[3]

top_indices = class_4_coefficients.argsort()[-10:][::-1]

for index in top_indices:
    print(feature_names[index], class_4_coefficients[index])

myocardial 2.640954096786267
endocarditis 2.617332460497639
hypertensive 2.3992150338901443
pericardial 2.3987827430432964
raynaud 2.389928332789421
hypertension 2.384511339240756
thromboembolic 2.1773300569439127
cardiovascular 2.130982243747795
arteritis 1.9927245434614782
vasculitis 1.9013245943659547