# Transformers Error Analysis

### 1. Add imports

In [2]:
import pandas as pd 
import torch 

from torch.utils.data import Dataset, DataLoader
from transformers import (AutoTokenizer, AutoModelForSequenceClassification, DataCollatorWithPadding)
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [3]:
df_test = pd.read_csv("../datasets/clinical_cases_test.csv")

X_test = df_test["medical_abstract"].tolist()

y_test = [
    label - 1 
    for label in df_test["condition_label"].tolist()
]

print(f"Test samples: {len(df_test)}")

Test samples: 2888

In [4]:
MODEL_PATH = "../models/biomedbert-medintake"

tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)

model = AutoModelForSequenceClassification.from_pretrained(MODEL_PATH)

device = torch.device(
    "mps" if torch.backends.mps.is_available() else "cpu"
)

model.to(device)

print(f"Device: {device}")

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Device: mps

In [5]:
test_encodings = tokenizer(
    X_test,
    trunction=True,
    max_length=256
)

print("Tokenization completed.")

Tokenization completed.

In [6]:
data_collator = DataCollatorWithPadding(
    tokenizer=tokenizer
)

In [7]:
class MedicalDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {
            key: torch.tensor(val[idx])
            for key, val in self.encodings.items()
        }

        item["labels"] = torch.tensor(self.labels[idx])

        return item


test_dataset = MedicalDataset(test_encodings, y_test)

print(f"Test samples: {len(test_dataset)}")

Test samples: 2888

In [8]:
test_loader = DataLoader(
    test_dataset,
    batch_size=8,
    collate_fn=data_collator
)

print(f"Batches: {len(test_loader)}")

Batches: 361

In [9]:
model.eval()

all_predictions = []
all_labels = []

with torch.no_grad():
    for batch in test_loader:
        batch = {
            key: value.to(device)
            for key, value in batch.items()
        }

        outputs = model(**batch)

        predictions = torch.argmax(outputs.logits, dim=1)

        all_predictions.extend(predictions.cpu().tolist())
        all_labels.extend(batch["labels"].cpu().tolist())

print(f"Predictions: {len(all_predictions)}")
print(f"Labels: {len(all_labels)}")

Predictions: 2888
Labels: 2888

In [10]:
errors = df_test.copy()

errors["true_label"] = all_labels
errors["predicted_label"] = all_predictions

errors = errors[
    errors["true_label"] != errors["predicted_label"]
]

print(f"Errors: {len(errors)}")

Errors: 1000

In [18]:
label_names = {
    0: "(1) Neoplasms",
    1: "(2) Digestive system diseases",
    2: "(3) Nervous system diseases",
    3: "(4) Cardiovascular diseases",
    4: "(5) General pathological conditions"
}

error_table = (
    errors
    .groupby(["true_label", "predicted_label"])
    .size()
    .reset_index(name="errors")
    .sort_values("errors", ascending=False)
    .reset_index(drop=True)
)

error_table["true_label"] = error_table["true_label"].map(label_names)
error_table["predicted_label"] = error_table["predicted_label"].map(label_names)

error_table = error_table.rename(columns={
    "true_label": "True class",
    "predicted_label": "Predicted class"
})

error_table

,True class,Predicted class,errors
0,(5) General pathological conditions,(4) Cardiovascular diseases,199
1,(5) General pathological conditions,(1) Neoplasms,161
2,(5) General pathological conditions,(2) Digestive system diseases,136
3,(5) General pathological conditions,(3) Nervous system diseases,99
4,(4) Cardiovascular diseases,(5) General pathological conditions,58
5,(3) Nervous system diseases,(5) General pathological conditions,55
6,(2) Digestive system diseases,(1) Neoplasms,44
7,(2) Digestive system diseases,(5) General pathological conditions,37
8,(3) Nervous system diseases,(1) Neoplasms,33
9,(3) Nervous system diseases,(4) Cardiovascular diseases,31
10,(1) Neoplasms,(5) General pathological conditions,31
11,(1) Neoplasms,(3) Nervous system diseases,29
12,(4) Cardiovascular diseases,(3) Nervous system diseases,18
13,(4) Cardiovascular diseases,(1) Neoplasms,14
14,(1) Neoplasms,(4) Cardiovascular diseases,13
15,(1) Neoplasms,(2) Digestive system diseases,11
16,(3) Nervous system diseases,(2) Digestive system diseases,10
17,(4) Cardiovascular diseases,(2) Digestive system diseases,9
18,(2) Digestive system diseases,(4) Cardiovascular diseases,7
19,(2) Digestive system diseases,(3) Nervous system diseases,5

In [20]:
errors_5_to_4 = errors[
    (errors["true_label"] == 4) &
    (errors["predicted_label"] == 3)
]

print(f"Errors (5) --> (4): {len(errors_5_to_4)}")

# visualizing full text rows to get better reasoning of vectorizer errors 
pd.set_option("display.max_colwidth", None)

errors_5_to_4[
    ["medical_abstract", "true_label", "predicted_label"]
].head(10)

Errors (5) --> (4): 199

,medical_abstract,true_label,predicted_label
35,"Epidural anaesthesia for labour and caesarean section in a parturient with a single ventricle and transposition of the great arteries. We describe a case of a 29-year-old parturient with a single ventricle and transposition of the great arteries who had lumbar epidural analgesia/anaesthesia with a local anaesthetic for labour, emergency Caesarean section and postoperative pain. Her outcome and that of her baby was successful. The anaesthetic techniques used in other parturients with similar congenital cardiac anomalies are reviewed.",4,3
50,Aberrant origin of the right coronary artery as a potential cause of sudden death: successful anatomical correction. A man with an aberrant right coronary artery and haemodynamically important prolapse of the mitral valve was successfully resuscitated. The aberrant right coronary artery was thought to be a possible cause of the cardiopulmonary arrest in this patient. Both lesions were corrected at a single operation.,4,3
75,Catheterization of coronary artery bypass graft from the descending aorta. The increasing frequency of reoperation for coronary artery disease has led to the use of a variety of grafts. This report describes the catheter technique for selective opacification of a saphenous vein graft from the descending thoracic aorta to the posterior coronary circulation.,4,3
91,"Severe hypertension after liver transplantation in alpha 1 antitrypsin deficiency. Five children with alpha 1 antitrypsin deficiency and terminal liver disease received liver grafts; all five became hypertensive and four developed hypertensive encephalopathy. There was evidence of renal disease preoperatively and renal biopsy specimens showed variable glomerulonephritic histology with IgA nephropathy in one, mesangial-proliferative changes in two, and mesangio-capillary glomerulonephritis type I in two. Four hypertensive episodes were preceded by a fall in creatinine clearance. The association of glomerulonephritis with alpha 1 antitrypsin deficiency in children is more common than has been recognised. Affected patients are prone to severe hypertension of probable renal origin after liver transplantation and the renal lesion may affect long term prognosis.",4,3
94,"Assessing the clinical effectiveness of preventive maneuvers: analytic principles and systematic methods in reviewing evidence and developing clinical practice recommendations. A report by the Canadian Task Force on the Periodic Health Examination. This paper examines a process for evaluating clinical effectiveness and developing recommendations in which systematic methods are used to review evidence from published clinical research and to reach sound conclusions about appropriate medical policy. The methodology addresses four important components of the analytic process: (1) the criteria that must be satisfied for a clinical practice to be considered effective; (2) proper methods for reviewing evidence from published clinical research to determine whether a clinical practice meets these criteria (including methods for performing comprehensive literature reviews, for judging the quality of individual studies, and for synthesizing or pooling the results of multiple studies); (3) theoretical and practical concerns in translating the results of the scientific review into sound clinical practice recommendations; and (4) the importance of documentation, guidelines, and other safeguards to minimize the effect the reviewers themselves have on the objectivity and consistency of the analytic methods.",4,3
98,"Caffeine and cardiac arrhythmias. PURPOSE: To review the evidence supporting the belief that caffeine causes cardiac arrhythmias. DATA SOURCES: Studies published since 1982 identified through computerized searches of MEDLINE, TOXLINE, and Chemical Abstracts and a review of bibliographies of relevant articles on the subject of caffeine and cardiac arrhythmias. STUDY SELECTION: All clinical studies examining caffeine as a cause of cardiac arrhythmias and a selection of basic science experiments to illustrate caffeine's effects in vitro. DATA EXTRACTION: Study quality was assessed and all available clinical data pertaining to caffeine as a cause of arrhythmias were summarized. RESULTS OF DATA ANALYSIS: In one electrophysiologic study, caffeine was associated with an increased susceptibility to provoked cardiac arrhythmias. In five placebo-controlled trials, caffeine in doses up to 500 mg daily (equivalent to 5 to 6 cups of coffee) did not increase the frequency or severity of ventricular arrhythmias. One large epidemiologic study reported an increase in the frequency of ventricular extrasystoles in persons consuming 9 or more cups of coffee daily. CONCLUSION: Moderate ingestion of caffeine does not increase the frequency or severity of cardiac arrhythmias in normal persons, patients with ischemic heart disease, or those with pre-existing serious ventricular ectopy.",4,3
175,"Clinical and electrophysiologic determinants, treatment and survival of patients with sustained malignant ventricular tachyarrhythmias occurring late after myocardial infarction To assess the clinical and electrophysiologic determinants, treatment and survival of patients with sustained malignant ventricular tachyarrhythmias late after myocardial infarction, a total of 108 patients (mean age 61 +/- 10 years) were studied. Thirty-two patients (Group I) had sustained ventricular tachyarrhythmias 8 to 60 days (mean 13 +/- 9) after acute myocardial infarction. The remaining 76 patients (Group II), who served as a control group, had no sustained ventricular tachyarrhythmias less than or equal to 60 days after infarction. The most significant independent determinants of sustained ventricular tachyarrhythmias late after infarction were the presence of late potentials (chi square = 16.07, p = 0.0001), defined as an abnormal signal-averaged QRS complex in association with an abnormal root-mean-square voltage in the terminal 40 ms of the QRS complex, and an abnormal ejection fraction of less than 40% (chi square = 10.09, p = 0.001). Sustained ventricular tachycardia was induced in 27 (96%) of 28 Group I patients. Among the 32 patients in Group I, antitachycardia therapy included antiarrhythmic drug therapy as the sole preventive measure in 14 (44%); map-guided surgery or coronary artery bypass surgery, or both, in 14 (44%) and the automatic cardioverter-defibrillator in 4 (12%). The arrhythmias were rendered noninducible in 83% of patients after map-guided surgery and in 41% after drug therapy. During a follow-up period of 20 +/- 14 months, five Group I patients (15%) had an arrhythmic event and four (9.3%) had a cardiac-related death. All five patients who had an arrhythmic event were receiving antiarrhythmic drug therapy.",4,3
179,"Increased Ca2+ signaling after alpha-adrenoceptor activation in vascular hypertrophy. In an effort to explain the increased sensitivity to agonists of hypertrophic vascular muscle, intracellular Ca2+ concentration ([Ca2+]i)-signaling mechanisms were studied in normal and hypertrophic rat aortas from normotensive and coarctation-hypertensive rats. Based on both fura 2 fluorescence and aequorin luminescence measurements, qualitatively different patterns of Ca2+ mobilization occur in normal and hypertrophic rat aortic muscle. Normal rat aortic muscle contracts to phenylephrine with little or no increase in [Ca2+]i, whereas the angiotensin II-induced contraction is accompanied by a marked [Ca2+]i transient. In contrast, hypertrophic rat aortic muscle shows a dramatic increase in Ca2+ signaling after phenylephrine stimulation. Moreover, both the amplitude of the angiotensin-induced [Ca2+]i transient and the contractile sensitivity to this agonist are decreased in the hypertrophic muscle. Our results strongly suggest that the amplitude of the [Ca2+]i transient after agonist stimulation determines the contractile sensitivity and that there is an altered coupling of the alpha-adrenoceptor in the hypertrophic vascular muscle.",4,3
188,"Therapy of diseased stroke-prone spontaneously hypertensive rats with nimodipine. We investigated the therapeutic effect of nimodipine or parathyroidectomy in old, diseased stroke-prone spontaneously hypertensive rats by observing 98 male 1-year-old rats over 5 months. After stroke had occurred, the rats were divided into three groups: 1) parathyroidectomy, 2) nimodipine, and 3) controls. In the nimodipine group, the rats survived longer than those in the other groups. Blood pressure of the controls did not differ from the nimodipine-treated and parathyroidectomy animals. The increase in calcium content of brain and kidney tissues and of plasma renin activity, urea, and creatinine was attenuated by nimodipine or parathyroidectomy. The histology of the kidneys revealed widespread fibrinoid necrosis of arteries in all rats. In the nimodipine-treated or parathyroidectomy groups, healing of the lesions was detectable. Cerebral lesions were mainly characterized by fibrinoid necrosis. Nimodipine-treated as well as parathyroidectomied animals showed significantly fewer hypertensive cerebral lesions. In old, diseased stroke-prone spontaneously hypertensive rats, therapy with nimodipine or parathyroidectomy increased their survival rate. The cerebrovascular and renovascular lesions of treated animals were attenuated, and morphologic signs of healing were observed. Reduction of calcium overload by nimodipine or parathyroidectomy, even in an advanced stage of disease, had a therapeutic effect.",4,3
197,"Long-term results of Ionescu-Shiley valve in the tricuspid position. A retrospective analysis of the long-term results of using the Ionescu-Shiley pericardial bioprosthesis in the tricuspid position was carried out on 73 patients (8 men, 65 women). Of these procedures, ten were tricuspid valve replacement alone and the remainder were in combination with other valve procedures. The mean follow-up was 9.6 years (range, 4 to 18 years). The mean age of the patients was 53 years (range, 27 to 78 years). Seventy-one of the patients suffered tricuspid valve dysfunction from rheumatic heart disease. There were 13 postoperative deaths (within 30 days), giving a mortality rate of 17.8%. The actuarial survival at 10 years was 71% +/- 4.2%. Of the survivors, 49 (79.6%) were in functional class I or II. Primary tissue valve failure in the tricuspid position occurred in 1 patient 12 years after implantation and required reoperation. In another patient bioprosthetic tricuspid valve endocarditis developed. There was no incidence of thromboembolic complications. We conclude that the Ionescu-Shiley pericardial bioprosthesis was a satisfactory prosthesis in the tricuspid position in patients with acquired valvar dysfunction.",4,3